homework_05/__init__.py
from . import app

__all__ = [
    "app",
]

homework_05/app.py
"""
Домашнее задание №5
Первое веб-приложение

создайте базовое приложение на Flask
создайте index view /
добавьте страницу /about/, добавьте туда текст
создайте базовый шаблон (используйте https://getbootstrap.com/docs/5.0/getting-started/introduction/#starter-template)
в базовый шаблон подключите статику Bootstrap 5 и добавьте стили, примените их
в базовый шаблон добавьте навигационную панель nav (https://getbootstrap.com/docs/5.0/components/navbar/)
в навигационную панель добавьте ссылки на главную страницу / и на страницу /about/ при помощи url_for
"""

from flask import Flask, render_template
from views.about import about_app

app = Flask(__name__)
app.register_blueprint(about_app, url_prefix="/about")


@app.route("/", endpoint='home')
def root():
    return render_template("index.html")


if __name__ == "__main__":
    app.run(debug=True)

homework_05/views/about.py
from flask import Blueprint, render_template, request, redirect, url_for
from werkzeug.exceptions import BadRequest, NotFound

about_app = Blueprint("about_app", __name__)


@about_app.route("/", endpoint="about")
def about():
    return render_template("about/index.html")

homework_05/templates/about/index.html
{% extends 'base.html' %}


{% block title %}
About
{% endblock %}

{% block body %}
<p class="lead">Page about FLASK homework_5</p>
{% endblock %}

homework_05/templates/base.html
<!doctype html>
<html lang="en">

<head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
                integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
                crossorigin="anonymous">
        <title>{% block title %}
                Base title
                {% endblock %}</title>
</head>

<body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                        <a class="navbar-brand" href="#">Navbar</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                        <li class="nav-item">
                                                <a class="nav-link active" aria-current="page"
                                                        href="{{ url_for('home') }}">Home</a>
                                        </li>
                                        <li class="nav-item">
                                                <a class="nav-link" href="{{ url_for('about_app.about') }}">About</a>
                                        </li>
                                </ul>
                                <form class="d-flex">
                                        <input class="form-control me-2" type="search" placeholder="Search"
                                                aria-label="Search">
                                        <button class="btn btn-outline-success" type="submit">Search</button>
                                </form>
                        </div>
                </div>
        </nav>
        <div class="container">
                {% block body %}
                Hello body
                {% endblock %}
        </div>

        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
                crossorigin="anonymous"></script>
</body>

</html>

homework_05/templates/index.html
{% extends 'base.html' %}


{% block title %}
Home
{% endblock %}

{% block body %}
<p class="lead">Hi! This is my home page</p>
{% endblock %}